layout_spectrum: 0.8135076875332743
typography_spectrum: 0.7918875208124518
color:
  brandStrength: 0.91713762935251
  lightness: 0.06304405815899372
  saturation: 0.756387579953298
  rhythmicContrast: 0.5158162442967296
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
name: megamagisk.com
